<section id="passardadosvisao">

    <div class="container wow fadeInUp">

        <div class="row">

            <div class="col-md-12">

                <h3 class="section-title">Passar dados para Visão</h3>

                <div class="section-title-divider"></div>

            </div>

        </div>

    </div>

    <div class="container wow fadeInUp">

        <div class="row">

            <div class="col-md-3">

                <div class="menu-lateral">

                    <button

                        type="button"
                        class="btn btn-gu"
                        ng-class="{'active': pd.dadoscontrolador}"
                        ng-click="altera( 'dadoscontrolador', 'pd' )"

                    >Dados do Controlador</button>

                    <button

                        type="button"
                        class="btn btn-gu mar-top10"
                        ng-class="{'active': pd.parametrosurl}"
                        ng-click="altera( 'parametrosurl', 'pd' )"

                    >Parametros da URL</button>

                    <button

                        type="button"
                        class="btn btn-gu mar-top10"
                        ng-class="{'active': pd.caminhovisao}"
                        ng-click="altera( 'caminhovisao', 'pd' )"

                    >Define o Caminho Visão</button>

                </div>

            </div>

            <div class="col-md-9 passardadosvisao-content conteudo-lateral" ng-if="pd.dadoscontrolador">

                <h2 class="passardadosvisao-title">Dados do Controlador</h2>

                <p class="primeirospassos-text">

                    É possível passar os dados do controlador para a visão, utilizando o método <code>$this->load->view('arquivo.php')</code>. <br><br>
                    
                    Veja o exemplo abaixo:

                    <h4>No Controlador</h4>

                    <?php

                        highlight_string('<?php

class primeirocontroladorControlador extends Controller
{

    public function indexAcao()
    {

        $parametros[\'framework\']= \'Guepardo\';
        $parametros[\'ano\']= \'2017\';

        $this->load->view(\'index.php\', $parametros);

    }

}

?>');

                    ?> <br><br>

                Os dados são passados dentro do array de <code>parametros</code>, e o mesmo é passado como o segundo parametro no método <code>visao</code>. <br>
                Para recuperar os dados na visão, basta passar o prefixo <code>$view_</code> mais o indice do array. <br><br>

                <?php

                        highlight_string('<?php

    $view_framework;
    $view_ano;

?>');

                ?> <br><br>

                É possível passar o dado em forma de array e rodar o <code>foreach</code> para recuperar cada dado.

                </p>

            </div>

            <div class="col-md-9 passardadosvisao-content conteudo-lateral" ng-if="pd.parametrosurl">

                <h2 class="passardadosvisao-title">Parametros da URL</h2>

                <p class="primeirospassos-text">

                    É possível recuperar parametros da url diretamente da visão. <br><br>

                    Para que isso esteja disponível basta deixar o <code>AUTOURLPAR_VISAO</code> como <code>true</code>, essa configuração está definido dentro de <code>config/config.php</code>. <br><br>

                    Para chamar o parametro da url, basta passar <code>$viewauto_</code>, por exemplo: <br>
                    <code>localhost/minhaaplicacao/meucontrolador/minhaacao/nome/guepardo</code>, nesse exemplo quero recuperar o parametro nome, então simplismente coloco <code>$viewauto_nome;</code> e o mesmo retornará <code>guepardo</code>.

                </p>

            </div>

            <div class="col-md-9 passardadosvisao-content conteudo-lateral" ng-if="pd.caminhovisao">

                <h2 class="passardadosvisao-title">Definir Caminho para a Visão</h2>

                <p class="primeirospassos-text">

                    Em alguns momentos pode surgir a necessidade de renderizar a visão de outro caminho/diretório e não do padrão que é <code>app/minhaaplicacao/visao/</code>. <br><br>

                    Para definir o caminho é necessário passar como terceiro parametro da <code>visão</code>, exemplo: <br><br>

                    <code>$this->load->view('index.html','',APP_PATCH.'/visao/visao_2/');</code>

                </p>

            </div>

        </div>

    </div>

</section>