<section id="entendamodelo">

    <div class="container wow fadeInUp">

        <div class="row">

            <div class="col-md-12">

                <h3 class="section-title">Entendendo sobre Modelo ( MODELS )</h3>

                <div class="section-title-divider"></div>

                <p class="section-description">

                    Sempre que você pensar em manipulação de dados, pense em model. Ele é responsável pela leitura e escrita de dados, e também de suas validações.

                </p>

            </div>

        </div>

    </div>

    <div class="container wow fadeInUp">

        <div class="row">

            <div class="col-md-5 entendamodelo-content">

                <img src="<?php echo CAMINHO ?>/app/framework/externos/img/mvc.jpg" class="img-responsive img-thumbnail">

            </div>

            <div class="col-md-7 entendamodelo-content">

                <h2 class="entendamodelo-title">Model</h2>

                <p class="entendamodelo-text">

                    Quando você desejar utilizar um modelo, o mesmo deve extender do modelo principal do framework: <code>GU_Model</code>.

                </p>

                <p class="entendamodelo-text">

                    O Guepardo trabalha com um padrão de prefixo e sufixo: <br>
                    - <code>PREFIXO</code>: Nome de base do controlador. <br>
                    - <code>SUFIXO</code>: Identificador padrão: "<code>Modelo</code>". <br>

                </p>

            </div>

        </div>

    </div>

</section>