<div class="row">

    <div class="col-lg-3 col-xs-6">

        <div class="small-box bg-aqua">

            <div class="inner">

                <h3>150</h3>

                <p>Novas Ordens</p>

            </div>

            <div class="icon">

                <i class="fa fa-shopping-bag"></i>

            </div>

            <a href="#" class="small-box-footer">Mais informações <i class="fa fa-arrow-circle-right"></i></a>

        </div>

    </div>

    <div class="col-lg-3 col-xs-6">

        <div class="small-box bg-green">

            <div class="inner">

                <h3>53<sup style="font-size: 20px">%</sup></h3>

                <p>Taxa de rejeição</p>

            </div>

            <div class="icon">

                <i class="fa fa-pie-chart"></i>

            </div>

            <a href="#" class="small-box-footer">Mais informações <i class="fa fa-arrow-circle-right"></i></a>

        </div>

    </div>

    <div class="col-lg-3 col-xs-6">

        <div class="small-box bg-yellow">

            <div class="inner">

                <h3>44</h3>

                <p>Registros de usuários</p>

            </div>

            <div class="icon">
                
                <i class="fa fa-user-plus"></i>

            </div>

            <a href="#" class="small-box-footer">Mais informações <i class="fa fa-arrow-circle-right"></i></a>

        </div>

    </div>

    <div class="col-lg-3 col-xs-6">

        <div class="small-box bg-red">

            <div class="inner">

                <h3>65</h3>

                <p>Visitantes Únicos</p>

            </div>

            <div class="icon">

                <i class="fa fa-pie-chart"></i>

            </div>

            <a href="#" class="small-box-footer">Mais informações <i class="fa fa-arrow-circle-right"></i></a>

        </div>

    </div>

</div>

<div class="row">
        
    <section class="col-lg-12">

        <div class="box box-success">

            <div class="box-header">

                <i class="fa fa-comments-o"></i>

                <h3 class="box-title">Chat</h3>

                <div class="box-tools pull-right" data-toggle="tooltip" title="Status">

                    <div class="btn-group" data-toggle="btn-toggle">

                        <button type="button" class="btn btn-default btn-sm active"><i class="fa fa-square text-green"></i>
                        </button>

                        <button type="button" class="btn btn-default btn-sm"><i class="fa fa-square text-red"></i></button>

                    </div>

                </div>

            </div>

            <div class="box-body chat" id="chat-box">

                <div class="item">

                    <img src="<?php echo EXTERNOS; ?>template/img/user4-128x128.jpg" alt="user image" class="online">

                    <p class="message">

                        <a href="#" class="name">

                            <small class="text-muted pull-right"><i class="fa fa-clock-o"></i> 2:15</small>
                            
                            Mike Doe

                        </a>

                        Gostaria de conhecê-lo para discutir as últimas notícias sobre a chegada do novo tema. Eles dizem que será um dos melhores temas do mercado

                    </p>

                    <div class="attachment">

                        <h4>Anexos:</h4>

                        <p class="filename">
                            
                            Tema-thumbnail-image.jpg

                        </p>

                        <div class="pull-right">
                            
                            <button type="button" class="btn btn-primary btn-sm btn-flat">Aberto</button>

                        </div>

                    </div>

                </div>

                <div class="item">

                    <img src="<?php echo EXTERNOS; ?>template/img/user3-128x128.jpg" alt="user image" class="offline">

                    <p class="message">

                        <a href="#" class="name">

                            <small class="text-muted pull-right"><i class="fa fa-clock-o"></i> 5:15</small>
                            Alexander Pierce

                        </a>

                        Gostaria de conhecê-lo para discutir as últimas notícias sobre a chegada do novo tema. Eles dizem que será um dos melhores temas do mercado

                    </p>

                </div>

            </div>

            <div class="box-footer">

                <div class="input-group">

                    <input class="form-control" placeholder="Digite a mensagem...">

                    <div class="input-group-btn">

                        <button type="button" class="btn btn-success"><i class="fa fa-plus"></i></button>

                    </div>

                </div>

            </div>

        </div>

        <div class="box box-info">

            <div class="box-header">

                <i class="fa fa-envelope"></i>

                <h3 class="box-title">E-mail rápido</h3>

                <div class="pull-right box-tools">

                    <button type="button" class="btn btn-info btn-sm" data-widget="remove" data-toggle="tooltip"
                    title="Remove">
                    
                    <i class="fa fa-times"></i></button>

                </div>

            </div>

            <div class="box-body">

                <form action="#" method="post">

                    <div class="form-group">

                        <input type="email" class="form-control" name="emailto" placeholder="E-mail para:">

                    </div>

                    <div class="form-group">

                        <input type="text" class="form-control" name="subject" placeholder="Sujeito">

                    </div>

                    <div>

                        <textarea class="textarea" placeholder="Mensagem" style="width: 100%; height: 125px; font-size: 14px; line-height: 18px; border: 1px solid #dddddd; padding: 10px;"></textarea>
                    
                    </div>

                </form>

            </div>

            <div class="box-footer clearfix">

                <button type="button" class="pull-right btn btn-default" id="sendEmail">Enviar <i class="fa fa-arrow-circle-right"></i></button>

            </div>

        </div>

    </section>

</div>