<footer id="footer">

    <div class="container">

        <div class="row">

            <div class="col-md-12">

                <div class="copyright">

                    &copy; Copyright <strong>Lucas Eduardo</strong>. Todos os direitos reservados.
                
                </div>

                <div class="credits">
                
                    Acesse o GitHub <a target="_blank" href="https://github.com/manualdeveloper">manual developer</a>

                    <br>

                    <a style="font-size: 20px;" target="_blank" href="https://www.youtube.com/channel/UCSuVlFnEHz6zsWzMQseDRGg" title="Canal no youtube">

                        <i class="fa fa-youtube"></i>

                    </a>

                </div>

            </div>

        </div>

    </div>

</footer>