<section id="criarcontrolador">

    <div class="container wow fadeInUp">

        <div class="row">

            <div class="col-md-12">

                <h3 class="section-title">Criando o Controlador</h3>

                <div class="section-title-divider"></div>

            </div>

        </div>

    </div>

    <div class="container wow fadeInUp">

        <div class="row">

            <div class="col-md-12 criarcontrolador-content">

                <h2 class="criarcontrolador-title">Criar Controller</h2>

                <p class="criarcontrolador-text">

                    Ao criar um controlador o mesmo deve se extender da classe do controlador principal, o <code>Controller</code>. <br>

                    Vamos criar um controlador chamado <code><strong>primeirocontroladorControlador.php</strong></code>, o mesmo tem que ser salvo no seguinte caminho: <code>aplicacao/app/site/controladores/</code> <br>
                    <strong class="font12">*Obs: Lembrando que o caminho é somente um exemplo, todos os controladores devem ser salvos dentro da pasta controladores.</strong>

                    <br><br>

                    <?php

                        highlight_string('<?php

class primeirocontroladorControlador extends Controller{

    public function indexAcao(){

        echo "FrameWork Guepardo";

    }

}

?>');

                    ?> <br><br>

                    Se tudo ocorreu corretamente, basta abrir no navegador, passando o controlador, por exemplo: <br>
                    <code>http://localhost/primeirocontrolador</code> e o mesmo irá mostrar na tela: "<strong>FrameWork Guepardo</strong>".

                </p>

            </div>

        </div>

    </div>

</section>