<aside class="main-sidebar">

    <section class="sidebar">

        <div class="user-panel">

            <div class="pull-left image">

                <img src="<?php echo EXTERNOS; ?>template/img/user2-160x160.jpg" class="img-circle" alt="User Image">

            </div>

            <div class="pull-left info">

                <p>Alexander Pierce</p>
                <a href="#"><i class="fa fa-circle text-success"></i> Online</a>

            </div>

        </div>
        
        <ul class="sidebar-menu" data-widget="tree">

            <li class="header">NAVEGAÇÃO PRINCIPAL</li>

            <li class="<?php echo ($this->router->controlador == 'index')? 'active' : ''; ?>">

                <a href="<?php echo CAMINHO; ?>">

                    <i class="fa fa-dashboard"></i> <span>Dashboard</span>

                </a>

            </li>

            <li class="<?php echo ($this->router->controlador == 'widgets')? 'active' : ''; ?>">

                <a href="<?php echo CAMINHO; ?>/widgets">

                    <i class="fa fa-th"></i> <span>Widgets</span>

                    <span class="pull-right-container">

                        <small class="label pull-right bg-green">novo</small>

                    </span>

                </a>

            </li>

            <li class="treeview">

                <a href="#">

                    <i class="fa fa-pie-chart"></i>

                    <span>Gráficos</span>

                    <span class="pull-right-container">

                        <i class="fa fa-angle-left pull-right"></i>

                    </span>

                </a>

                <ul class="treeview-menu">

                    <li><a href="#"><i class="fa fa-circle-o"></i> ChartJS</a></li>
                    <li><a href="#"><i class="fa fa-circle-o"></i> Morris</a></li>
                    <li><a href="#"><i class="fa fa-circle-o"></i> Flot</a></li>
                    <li><a href="#"><i class="fa fa-circle-o"></i> Inline charts</a></li>

                </ul>

            </li>

            <li>

                <a href="https://adminlte.io/themes/AdminLTE/index.html" target="_blank">

                    <i class="fa fa-book"></i> <span>Preview Admin LTE</span>

                </a>

            </li>

        </ul>

    </section>

</aside>